name: Build and deploy code

on: 
  push:
    branches: 
      - "main"

jobs:
  run_ubuntu:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v4
      - name: Install Python v3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Update pip
        run: pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-24.04-arm
    needs: [run_ubuntu]

    steps:
      - name: Deploy to EC2 instance via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22

          script: |
            cd /home/ubuntu/Portfolio-Ecommerce-backend

            git checkout main
            git reset --hard HEAD
            git clean -fd

            git pull origin main

            echo "Stopping existing containers..."
            docker-compose down

            echo "Building and starting new containers..."
            docker-compose up --build -d

            echo "Cleaning up old Docker images..."
            docker image prune -af